# Generated by Django 5.0.14 on 2025-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковской картой')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
