# Generated by Django 5.0.14 on 2025-06-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
