# Generated by Django 5.0.14 on 2025-06-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0006_remove_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Корзина'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
