# Generated by Django 5.0.14 on 2025-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0012_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, verbose_name='Материалы'),
        ),
    ]
