# Generated by Django 5.0.14 on 2025-06-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0013_product_depth_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bead_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет бусин'),
        ),
    ]
