# Generated by Django 5.0.14 on 2025-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0014_product_bead_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hardware_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет фурнитуры'),
        ),
    ]
