# Generated by Django 5.0.14 on 2025-07-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0015_product_hardware_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
