# Generated by Django 5.0.14 on 2025-06-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Новый пароль (зашифрованный)'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_verification_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Токен подтверждения пароля'),
        ),
    ]
